### ISSUE TITLE
The robot has been installed, how do I use it?

### ISSUE THREAD

**Issue by klcb2010** [s-nagaev/chibi#30]
![截屏图片](https://github.com/s-nagaev/chibi/assets/32628414/c14853b4-9a2d-40ee-bc03-379316f56517)

**Comment by s-nagaev** [comment]
@klcb2010 Since you were able to launch the bot, it means you provided a valid `TELEGRAM_BOT_TOKEN`, obtained from https://t.me/BotFather when creating the bot. Basically, you did everything necessary: now you can write to your bot in Telegram, and it will reply to you :)

**Comment by s-nagaev** [comment]
Answered here: https://github.com/s-nagaev/hiroshi/issues/34
