### ISSUE TITLE
Ask bot by custom name

### ISSUE THREAD

**Issue by leksuss** [s-nagaev/chibi#8]
Hi!
Great job! It would be awesome if the bot only responded when addressed directly by name or in response to its messages, and the name could be customized. For example, you could address the bot like this:
```
Chibi, what's the radius of the Earth?
```
This would definitely make the interaction with the bot much more personalized and user-friendly.

**Comment by s-nagaev** [comment]
Hi! Thank you!

Do you mean the case when the user interacts with the bot in a group chat?

**Comment by leksuss** [comment]
> Do you mean the case when the user interacts with the bot in a group chat?

Yes, that's exactly what I had in mind.

**Comment by s-nagaev** [comment]
Got it! Nice catch! Will try to do it today :)

I never face such a problem cause [privacy mode](https://core.telegram.org/bots#privacy-mode) for my bot is enabled. But yeah, when disabled, the bot will receive every single message sent to the group chat.

**Comment by s-nagaev** [comment]
Done :)
